apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radarr.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PUID
              value: "{{ .Values.radarr.puid }}"
            - name: PGID
              value: "{{ .Values.radarr.pgid }}"
            - name: TZ
              value: "{{ .Values.radarr.timezone }}"
            - name: UMASK_SET
              value: "{{ .Values.radarr.umask_set}}"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          iscsi:
            targetPortal: 10.10.10.14:3260
            iqn: iqn.2020-05.risp.in:radarr
            lun: 1
            fsType: ext4
            readOnly: false
        - name: downloads
          nfs:
            server: "{{ .Values.radarr.volumes.downloads.server }}" 
            path: "{{ .Values.radarr.volumes.downloads.path }}" 
