apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7878
      protocol: TCP
      name: radarr
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.externalIp }}
  externalTrafficPolicy: {{ .Values.service.trafficPolicy }}
  {{- end }}
