apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "jackett.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "jackett.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jackett.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jackett
              containerPort: 9117
              protocol: TCP
          env:
            - name: PUID
              value: "{{ .Values.jackett.puid }}"
            - name: PGID
              value: "{{ .Values.jackett.pgid }}"
            - name: TZ
              value: "{{ .Values.jackett.timezone }}"
            - name: UMASK_SET
              value: "{{ .Values.jackett.umask_set}}"
          volumeMounts:
            - mountPath: /config
              name: config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          nfs:
            server: "{{ .Values.jackett.volumes.config.server }}"
            path: "{{ .Values.jackett.volumes.config.path }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
